export declare const COLOR_RED = "var(--color-red)";
export declare const COLOR_BLUE = "var(--color-blue)";
export declare const COLOR_BLACK = "var(--color-black)";
export declare const COLOR_WHITE = "var(--color-white)";
export declare const COLOR_GRAY = "var(--color-gray)";
export declare const COLOR_YELLOW = "var(--color-yellow)";
export declare const COLOR_LIST_MARKER = "var(--color-list-marker)";
export declare const SPACING_0 = "var(--spacing-0)";
export declare const SPACING_1 = "var(--spacing-1)";
export declare const SPACING_2 = "var(--spacing-2)";
export declare const SPACING_3 = "var(--spacing-3)";
export declare const TEXT_SMALL = "var(--text-size-small)";
export declare const TEXT_MEDIUM = "var(--text-size-medium)";
export declare const TEXT_LARGE = "var(--text-size-large)";
export declare enum Tokens {
    COLOR_RED = "var(--color-red)",
    COLOR_BLUE = "var(--color-blue)",
    COLOR_BLACK = "var(--color-black)",
    COLOR_WHITE = "var(--color-white)",
    COLOR_YELLOW = "var(--color-yellow)",
    COLOR_GRAY = "var(--color-gray)",
    COLOR_LIGHTGRAY = "var(--color-lightrgray",
    COLOR_LIST_MARKER = "var(--color-list-marker)",
    SPACING_0 = "var(--spacing-0)",
    SPACING_1 = "var(--spacing-1)",
    SPACING_2 = "var(--spacing-2)",
    SPACING_3 = "var(--spacing-3)",
    TEXT_SMALL = "var(--text-size-small)",
    TEXT_MEDIUM = "var(--text-size-medium)",
    TEXT_LARGE = "var(--text-size-large",
    BOX_BORDER_RADIUS = "var(--box-border-radius)"
}
//# sourceMappingURL=index.d.ts.map